"""add_comments_and_feature_fields

Revision ID: d84b121c6262
Revises: 7cfc777d46b1
Create Date: 2025-11-27 18:56:44.462343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84b121c6262'
down_revision: Union[str, None] = '7cfc777d46b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.add_column('feature_requests', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('feature_requests', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('feature_requests', sa.Column('approval_notes', sa.Text(), nullable=True))
    op.add_column('feature_requests', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_requests', 'acceptance_criteria')
    op.drop_column('feature_requests', 'approval_notes')
    op.drop_column('feature_requests', 'rejection_reason')
    op.drop_column('feature_requests', 'tags')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
